apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm-tailscale.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-tailscale.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "helm-tailscale.fullname" . }}
  apiGroup: rbac.authorization.k8s.io