{{ if eq .Values.tailscale.existingSecret false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-tailscale.fullname" . }}
type: Opaque
stringData:
  TS_AUTHKEY: "{{ .Values.tailscale.key }}"
{{ end }}