apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-tailscale.serviceAccountName" . }}
  labels:
    {{- include "helm-tailscale.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}